title: Eder Lara Trujillo
logo: /assets/img/eddy.jpg
description: Desarrollador MEAN | Máster Big-Data
phone: +57 3115780589 - 318 8622612
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
